Enhance local allgather for multiple rounds
alpa-projects/alpa pull request #356
Opened 2022-03-09 07:37 UTC by ZYHowell

2022-03-11 10:29 UTC, merrymercy requested changes
This part is getting very complicated and hard to follow. Let us try to organize it better.

1. Move the description of the algorithm from github posts to the code comments. Add a more high-level algorithm description at the beginning of the file.
2. Define important data structure at the very beginning of the file. Move utility functions and class (e.g.,` _suffix_prod`) to the end of the file.
3. Create unit tests in `test_cross_mesh_resharding.py`. In each test case,
    1. explicitly create a `ReshardingTask`
    2. compile a resharding strategy
    3. assert the optimizations are applied (e.g. load balance, local all-gather)
    4. run it and test the correctness
   In the future, a new optimization should come with new test cases, so we know what cases can be optimized by the new optimization.

2022-03-11 10:29 UTC, merrymercy commented on alpa/pipeline_parallel/decentralized_distributed_runtime.py
> +            # TODO(yonghao)
what's this?

2022-03-12 02:09 UTC, zhisbug commented
I probably need a while to review this PR :) @ZYHowell

2022-03-14 15:28 UTC, ZYHowell commented
>     3. Create unit tests in `test_cross_mesh_resharding.py`. In each test case,
>        
>        1. explicitly create a `ReshardingTask`
>        2. compile a resharding strategy
>        3. assert the optimizations are applied (e.g. load balance, local all-gather)
>        4. run it and test the correctness
> 
> 
> In the future, a new optimization should come with new test cases, so we know what cases can be optimized by the new optimization.

See https://github.com/alpa-projects/alpa/pull/360.

2022-04-21 18:24 UTC, merrymercy commented
Let us try to get this reviewed or merged soon

2022-04-21 18:24 UTC, merrymercy commented
Let us try to get this reviewed or merged soon. @zhisbug @ZYHowell

2022-05-03 06:01 UTC, zhisbug approved these changes

2022-05-03 06:20 UTC, merged