[Alpa + Ray] adding the placement group
alpa-projects/alpa pull request #634
Opened 2022-08-03 21:35 UTC by JiahaoYao

This PR is to make use of placement group to create meshworkers. This new approach gives alpa more freedom to allocate the resources. 

Previous issue: #618 

- [x] adding the placement to replace `node_resources: 1e-3` 
- [ ] figure out which parts of the node is not necessary after using the placement.

----
benefits: 
- [x] resource will be homogeneous now, i.e. `{gpu: 2}` can be on node A or B or C, but `{gpu: 2, ip_A: 1e-3}` can only be on node A.
- [ ] potentially this leads to more easier implementation of elastic training. (i.e. using ray to deal with the resource management.)

2022-08-03 21:37 UTC, JiahaoYao commented
there should be a much elegant approach to this, like some of ip_address might not be needed now. probably we can remove that to make the code minimal.

2022-08-03 21:58 UTC, JiahaoYao commented
the ci failed here.
```python
test_4gpu_allgather (pipeline_parallel.test_cross_mesh_resharding.ReshardingTest) ... *** SIGTERM received at time=1659563677 on cpu 13 ***
PC: @     0x7efc99ea3065  (unknown)  pthread_cond_timedwait@@GLIBC_2.3.2
    @     0x7efc99ea7980  (unknown)  (unknown)
[2022-08-03 21:54:37,918 E 1495 1495] logging.cc:325: *** SIGTERM received at time=1659563677 on cpu 13 ***
[2022-08-03 21:54:37,919 E 1495 1495] logging.cc:325: PC: @     0x7efc99ea3065  (unknown)  pthread_cond_timedwait@@GLIBC_2.3.2
[2022-08-03 21:54:37,919 E 1495 1495] logging.cc:325:     @     0x7efc99ea7980  (unknown)  (unknown)

Timeout after 1000 seconds when running pipeline_parallel/test_cross_mesh_resharding.py
Fail. Time elapsed: 1033.91s
```

2022-08-04 05:38 UTC, merrymercy commented
> the ci failed here.
> 
> ```python
> test_4gpu_allgather (pipeline_parallel.test_cross_mesh_resharding.ReshardingTest) ... *** SIGTERM received at time=1659563677 on cpu 13 ***
> PC: @     0x7efc99ea3065  (unknown)  pthread_cond_timedwait@@GLIBC_2.3.2
>     @     0x7efc99ea7980  (unknown)  (unknown)
> [2022-08-03 21:54:37,918 E 1495 1495] logging.cc:325: *** SIGTERM received at time=1659563677 on cpu 13 ***
> [2022-08-03 21:54:37,919 E 1495 1495] logging.cc:325: PC: @     0x7efc99ea3065  (unknown)  pthread_cond_timedwait@@GLIBC_2.3.2
> [2022-08-03 21:54:37,919 E 1495 1495] logging.cc:325:     @     0x7efc99ea7980  (unknown)  (unknown)
> 
> Timeout after 1000 seconds when running pipeline_parallel/test_cross_mesh_resharding.py
> Fail. Time elapsed: 1033.91s
> ```

Sometimes the CI is not very stable, you can re-trigger it by pushing a new dummy commit.

2022-08-04 15:45 UTC, JiahaoYao commented
```python
test_simple_pipeshard (torch_frontend.test_simple.TorchSimpleTest) ... *** SIGTERM received at time=1659597164 on cpu 3 ***
PC: @     0x7f9eaa476065  (unknown)  pthread_cond_timedwait@@GLIBC_2.3.2
    @     0x7f9eaa47a980  (unknown)  (unknown)
[2022-08-04 07:12:44,499 E 47542 47542] logging.cc:325: *** SIGTERM received at time=1659597164 on cpu 3 ***
[2022-08-04 07:12:44,499 E 47542 47542] logging.cc:325: PC: @     0x7f9eaa476065  (unknown)  pthread_cond_timedwait@@GLIBC_2.3.2
[2022-08-04 07:12:44,499 E 47542 47542] logging.cc:325:     @     0x7f9eaa47a980  (unknown)  (unknown)

Timeout after 1000 seconds when running torch_frontend/test_simple.py
Fail. Time elapsed: 2686.85s
```
ci issues?

2022-08-04 16:30 UTC, JiahaoYao commented
```python
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
2022-08-04 15:48:59.793213: F external/org_tensorflow/tensorflow/compiler/xla/python/xla.cc:86] Check failed: tensorflow::RegisterNumpyBfloat16() 
/test_alpa_docker_entrypoint.sh: line 40:   505 Aborted                 (core dumped) python run_all.py
Error: Process completed with exit code 134.
```

2022-08-04 16:42 UTC, JiahaoYao commented
^ this error shows up again? is that the version of package issue?

2022-08-04 17:21 UTC, JiahaoYao commented
it seems like you might need to update numpy 
- https://github.com/tensorflow/tensorflow/issues/47117
- https://github.com/freqtrade/freqtrade/issues/4281

2022-08-04 18:09 UTC, JiahaoYao commented
@merrymercy any suggestions here to trouble-shoot here?

2022-08-05 05:27 UTC, JiahaoYao commented
```python
In file included from /python3.7-env/lib/python3.7/site-packages/torch/include/c10/core/InferenceMode.h:4:0,
                 from /python3.7-env/lib/python3.7/site-packages/torch/include/c10/core/TensorImpl.h:6,
                 from /python3.7-env/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:20,
                 from /python3.7-env/lib/python3.7/site-packages/torch/include/ATen/core/ivalue.h:4,
                 from /python3.7-env/lib/python3.7/site-packages/torch/include/ATen/core/stack.h:5,
                 from /python3.7-env/lib/python3.7/site-packages/torch/include/ATen/core/boxing/KernelFunction.h:3,
                 from /python3.7-env/lib/python3.7/site-packages/torch/include/ATen/core/dispatch/Dispatcher.h:4,
                 from /functorch/functorch/csrc/Interpreter.h:9,
                 from /functorch/functorch/csrc/ADInterpreters.h:2,
                 from /functorch/functorch/csrc/ADInterpreters.cpp:1:
/python3.7-env/lib/python3.7/site-packages/torch/include/c10/core/GradMode.h: In function ‘void at::functorch::autogradBasedTransformSendToNext(const c10::OperatorHandle&, torch::jit::Stack*, int64_t, at::functorch::TransformType, c10::optional<bool>, c10::optional<bool>)’:
/python3.7-env/lib/python3.7/site-packages/torch/include/c10/core/GradMode.h:20:27: warning: ‘*((void*)& grad_guard +1)’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     GradMode::set_enabled(prev_mode);
                           ^~~~~~~~~
/functorch/functorch/csrc/ADInterpreters.cpp:125:31: note: ‘*((void*)& grad_guard +1)’ was declared here
   optional<c10::AutoGradMode> grad_guard;
                               ^~~~~~~~~~
In file included from /python3.7-env/lib/python3.7/site-packages/torch/include/c10/core/InferenceMode.h:4:0,
                 from /python3.7-env/lib/python3.7/site-packages/torch/include/c10/core/TensorImpl.h:6,
                 from /python3.7-env/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:20,
                 from /python3.7-env/lib/python3.7/site-packages/torch/include/ATen/core/ivalue.h:4,
                 from /python3.7-env/lib/python3.7/site-packages/torch/include/ATen/core/stack.h:5,
                 from /python3.7-env/lib/python3.7/site-packages/torch/include/ATen/core/boxing/KernelFunction.h:3,
                 from /python3.7-env/lib/python3.7/site-packages/torch/include/ATen/core/dispatch/Dispatcher.h:4,
                 from /functorch/functorch/csrc/Interpreter.h:9,
                 from /functorch/functorch/csrc/ADInterpreters.h:2,
                 from /functorch/functorch/csrc/ADInterpreters.cpp:1:
/python3.7-env/lib/python3.7/site-packages/torch/include/c10/core/GradMode.h:39:53: warning: ‘*((void*)& fw_grad_guard +1)’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     AutogradState::get_tls_state().set_fw_grad_mode(prev_mode);
                                                     ^~~~~~~~~
/functorch/functorch/csrc/ADInterpreters.cpp:129:33: note: ‘*((void*)& fw_grad_guard +1)’ was declared here
   optional<c10::AutoFwGradMode> fw_grad_guard;
                                 ^~~~~~~~~~~~~
In file included from /functorch/functorch/csrc/BatchRulesHelper.h:14:0,
                 from /functorch/functorch/csrc/BatchRulesActivation.cpp:7:
/functorch/functorch/csrc/BatchingMetaprogramming.h:9:10: fatal error: ATen/VmapGeneratedPlumbing.h: No such file or directory
 #include <ATen/VmapGeneratedPlumbing.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
/python3.7-env/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
/python3.7-env/lib/python3.7/site-packages/setuptools/command/easy_install.py:160: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
/python3.7-env/lib/python3.7/site-packages/torch/utils/cpp_extension.py:411: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
error: command '/usr/bin/gcc' failed with exit code 1
The command '/bin/bash -c source python3.7-env/bin/activate   && pip install torch torchdistx --pre --extra-index-url https://download.pytorch.org/whl/nightly/cpu   && pushd /functorch && python setup.py install && popd' returned a non-zero code: 1
```
after merge the master

2022-08-06 06:30 UTC, JiahaoYao commented
```python
test_simple_pipeshard (torch_frontend.test_simple.TorchSimpleTest) ... *** SIGTERM received at time=1659767269 on cpu 17 ***
PC: @     0x7f44b76c4065  (unknown)  pthread_cond_timedwait@@GLIBC_2.3.2
    @     0x7f44b76c8980  (unknown)  (unknown)
[2022-08-06 06:27:49,991 E 47676 47676] logging.cc:325: *** SIGTERM received at time=1659767269 on cpu 17 ***
[2022-08-06 06:27:49,991 E 47676 47676] logging.cc:325: PC: @     0x7f44b76c4065  (unknown)  pthread_cond_timedwait@@GLIBC_2.3.2
[2022-08-06 06:27:49,991 E 47676 47676] logging.cc:325:     @     0x7f44b76c8980  (unknown)  (unknown)

Timeout after 1000 seconds when running torch_frontend/test_simple.py
Fail. Time elapsed: 2635.12s
```

2022-08-06 07:58 UTC, merrymercy commented
The torch CI seems to work in this PR https://github.com/alpa-projects/alpa/pull/637
If you still meet errors, you can try to disable the torch unit tests by changing this line
https://github.com/alpa-projects/alpa/blob/66b841a5e7b8b5481c678f4db826480adda59d1a/docker/scripts/test_alpa_docker_entrypoint.sh#L40
to
```
python run_all.py --skip-pattern torch
```

2022-08-06 12:17 UTC, JiahaoYao commented
okay, i will remove torch for now. it seems it can not get through `torch_frontend/test_simple.py`.

2022-08-06 12:51 UTC, JiahaoYao commented
if i skip pytorch, the ci is green.

2022-08-06 19:25 UTC, JiahaoYao commented
```python
test_simple_pipeshard (torch_frontend.test_simple.TorchSimpleTest) ... *** SIGTERM received at time=1659793149 on cpu 4 ***
PC: @     0x7f3a8d922065  (unknown)  pthread_cond_timedwait@@GLIBC_2.3.2
    @     0x7f3a8d926980  (unknown)  (unknown)
[2022-08-06 13:39:09,282 E 47735 47735] logging.cc:325: *** SIGTERM received at time=1659793149 on cpu 4 ***
[2022-08-06 13:39:09,282 E 47735 47735] logging.cc:325: PC: @     0x7f3a8d922065  (unknown)  pthread_cond_timedwait@@GLIBC_2.3.2
[2022-08-06 13:39:09,282 E 47735 47735] logging.cc:325:     @     0x7f3a8d926980  (unknown)  (unknown)

Timeout after 1000 seconds when running torch_frontend/test_simple.py
Fail. Time elapsed: 2696.62s
Error: Process completed with exit code 255.
```

2022-08-08 01:39 UTC, merrymercy commented
Let me know when this PR is ready for review and merge

2022-08-08 06:03 UTC, JiahaoYao commented
I could not figure out the error of the `pytorch/frontend`. this currently blocks me.

2022-08-08 08:29 UTC, merrymercy commented
Can you re-produce the errors locally? If your change works locally, we can disable pytorch unit tests and merge this PR.

2022-08-10 22:52 UTC, JiahaoYao commented
i was spending time to look into the issue and find the issue stemming from the ip address and the ip address from the bundle does not match? 


```python
ic| bundle_ips: ['10.0.2.181']
    bundle_specs: [{'CPU': 1.0, 'GPU': 4.0}]
    device_ips: ['10.0.2.111']
ic| bundle_ips: ['10.0.2.111']
    bundle_specs: [{'CPU': 1.0, 'GPU': 4.0}]
    device_ips: ['10.0.2.181']
Exception in thread Thread-8:
Traceback (most recent call last):
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    self.run()
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/threading.py", line 870, in run
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/alpa/device_mesh.py", line 1842, in launch_func
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/alpa/device_mesh.py", line 1842, in launch_func
    physical_meshes[i] = sliced_virtual_meshes[i].get_physical_mesh(i)
    physical_meshes[i] = sliced_virtual_meshes[i].get_physical_mesh(i)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/alpa/device_mesh.py", line 1822, in get_physical_mesh
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/alpa/device_mesh.py", line 1822, in get_physical_mesh
    self.launched_physical_mesh = DistributedPhysicalDeviceMesh(
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/alpa/device_mesh.py", line 943, in __init__
    self.launched_physical_mesh = DistributedPhysicalDeviceMesh(
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/alpa/device_mesh.py", line 943, in __init__
    self._launch_xla_servers()
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/alpa/device_mesh.py", line 971, in _launch_xla_servers
    self._launch_xla_servers()
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/alpa/device_mesh.py", line 971, in _launch_xla_servers
    device_bundle_idx_list = get_bundle_idx(self._placement_group,
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/alpa/util.py", line 1456, in get_bundle_idx
    device_bundle_idx_list = get_bundle_idx(self._placement_group,
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/alpa/util.py", line 1456, in get_bundle_idx
    sorted_bundle_idx = [bundle_ip2idx[ip] for ip in device_ips]
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/alpa/util.py", line 1456, in <listcomp>
    sorted_bundle_idx = [bundle_ip2idx[ip] for ip in device_ips]
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/alpa/util.py", line 1456, in <listcomp>
    sorted_bundle_idx = [bundle_ip2idx[ip] for ip in device_ips]
KeyError: '10.0.2.181'
    sorted_bundle_idx = [bundle_ip2idx[ip] for ip in device_ips]
KeyError: '10.0.2.111'
```

the trouble-shooting is either we specify the ip address for the bundle or get the ip address from the bundle and reset the ip address.

2022-08-10 23:06 UTC, JiahaoYao commented
the issue comes from here 

https://github.com/alpa-projects/alpa/blob/611069f5d9f1afa5f5805a822e146dfc7b0f7041/alpa/pipeline_parallel/stage_construction.py#L697-L704

2022-08-11 03:34 UTC, JiahaoYao commented
```python
test_simple_pipeshard (torch_frontend.test_simple.TorchSimpleTest) ... ERROR

Stderr:
/build/alpa/tests/torch_frontend/test_simple.py:32: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  params[name_map[f"{k}.weight"]] = torch.nn.init.xavier_uniform(
/build/alpa/tests/torch_frontend/test_simple.py:34: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  params[name_map[f"{k}.bias"]] = torch.nn.init.normal(
WARNING:alpa.pipeline_parallel.layer_construction:Too few non-trivial ops (dot, conv), which may influence auto-sharding performance
WARNING:alpa.pipeline_parallel.layer_construction:Too few non-trivial ops (dot, conv), which may influence auto-sharding performance
test_simple_shard (torch_frontend.test_simple.TorchSimpleTest) ... ok

======================================================================
ERROR: test_simple_pipeshard (torch_frontend.test_simple.TorchSimpleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 890, in _bootstrap

    self._bootstrap_inner()
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/build/alpa/alpa/util.py", line 907, in _target_func
    ret_value.append(func(*args, **(kwargs or {})))
  File "run_all.py", line 54, in run_one_file
    p.start()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 121, in start
Stdout:
GradTrackingTensor(lvl=1, value=
    tensor([[-0.6950,  1.3434, -0.5023,  ..., -0.2491, -0.9815,  1.1239],
            [-2.1546,  1.2867, -0.3093,  ..., -0.2203, -1.1223,  1.1862],
            [ 0.0064, -0.5891,  0.2085,  ..., -0.7070, -1.1262, -2.0460],
            ...,
            [-0.0905,  0.5096, -0.1068,  ...,  3.4648, -0.7828,  0.4826],
            [ 1.4160, -0.1553,  0.5046,  ...,  1.7814,  1.3040, -1.3981],
            [ 1.1131, -1.5573,  0.4699,  ..., -0.2341,  1.2621, -0.4734]])
)
Iter: 0, Loss: 2.319499
GradTrackingTensor(lvl=1, value=
    tensor([[ 8.4854e-01, -1.9400e+00, -7.0707e-01,  ..., -1.2673e-01,
              3.2172e-01, -1.9653e+00],
            [-8.9785e-02, -3.9805e-01,  7.3669e-01,  ..., -2.8131e-01,
             -2.[652](https://github.com/alpa-projects/alpa/runs/7779602899?check_suite_focus=true#step:6:653)2e-01,  4.9333e-01],
            [-1.2561e-03, -2.0034e-01, -5.4852e-01,  ...,  1.4437e+00,
              2.0120e-01, -9.6020e-01],
            ...,
            [ 3.2625e-01, -7.0343e-01, -1.3036e-01,  ..., -1.7950e+00,
              4.5679e-01, -2.4196e-01],
    self._popen = self._Popen(self)
  File "/usr/local/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/local/lib/python3.8/multiprocessing/context.py", line 276, in _Popen
    return Popen(process_obj)
  File "/usr/local/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/lib/python3.8/multiprocessing/popen_fork.py", line 75, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "run_all.py", line 49, in func
    ret = unittest.main(module=None, argv=["", "-vb"] + [filename])
  File "/usr/local/lib/python3.8/unittest/main.py", line 101, in __init__
    self.runTests()
  File "/usr/local/lib/python3.8/unittest/main.py", line 271, in runTests
    self.result = testRunner.run(self.test)
  File "/usr/local/lib/python3.8/unittest/runner.py", line 176, in run
    test(result)
  File "/usr/local/lib/python3.8/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/local/lib/python3.8/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/local/lib/python3.8/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/local/lib/python3.8/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/local/lib/python3.8/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/local/lib/python3.8/unittest/suite.py", line 122, in run
            [-7.9334e-01,  1.6535e+00,  5.8866e-01,  ..., -3.4754e-01,
              3.8894e-01,  9.4643e-01],
            [ 3.6438e-01, -4.4454e-01,  6.1995e-03,  ...,  9.4797e-01,
              5.7284e-01,  8.5693e-01]])
)
Iter: 1, Loss: 2.241855
FX IR code (cleaned): 
def forward(self, x):
    linear1_weight : torch.Tensor = self.linear1.weight
    linear1_bias : torch.Tensor = self.linear1.bias
    linear = torch._C._nn.linear(x, linear1_weight, linear1_bias)
    x = linear1_weight = linear1_bias = None
    linear2_weight : torch.Tensor = self.linear2.weight
    linear2_bias : torch.Tensor = self.linear2.bias
    linear_1 = torch._C._nn.linear(linear, linear2_weight, linear2_bias)
    linear = linear2_weight = linear2_bias = None
    linear3_weight : torch.Tensor = self.linear3.weight
    linear3_bias : torch.Tensor = self.linear3.bias
    linear_2 = torch._C._nn.linear(linear_1, linear3_weight, linear3_bias)
    linear_1 = linear3_weight = linear3_bias = None
    linear4_weight : torch.Tensor = self.linear4.weight
    linear4_bias : torch.Tensor = self.linear4.bias
    linear_3 = torch._C._nn.linear(linear_2, linear4_weight, linear4_bias)
    linear_2 = linear4_weight = linear4_bias = None
    return linear_3

JAX function code: 
def _alpa_forward_func(params, bufs, x):
    linear1_weight = params['linear1.weight']
    linear1_bias = params['linear1.bias']
    linear = torch.nn.functional.linear(x, linear1_weight, linear1_bias)
    x = linear1_weight = linear1_bias = None
    linear2_weight = params['linear2.weight']
    linear2_bias = params['linear2.bias']
    linear_1 = torch.nn.functional.linear(linear, linear2_weight, linear2_bias)
    linear = linear2_weight = linear2_bias = None
    linear3_weight = params['linear3.weight']
    linear3_bias = params['linear3.bias']
    linear_2 = torch.nn.functional.linear(linear_1, linear3_weight, linear3_bias)
    linear_1 = linear3_weight = linear3_bias = None
    linear4_weight = params['linear4.weight']
    linear4_bias = params['linear4.bias']
    linear_3 = torch.nn.functional.linear(linear_2, linear4_weight, linear4_bias)
    test(result)
  File "/usr/local/lib/python3.8/unittest/case.py", line 736, in __call__
    return self.run(*args, **kwds)
  File "/usr/local/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/usr/local/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/build/alpa/tests/torch_frontend/test_simple.py", line 76, in test_simple_pipeshard
    train_torch_module(pt_module_gen, weight_init_func, dataloader,
  File "/build/alpa/alpa/torch/trainer.py", line 99, in train_torch_module
    state = create_train_state()
  File "/python3.8-env/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/build/alpa/alpa/api.py", line 106, in __call__
    self._decode_args_and_get_executable(*args))
  File "/build/alpa/alpa/api.py", line 176, in _decode_args_and_get_executable
    executable = _compile_parallel_executable(f, in_tree, out_tree_hashable,
  File "/python3.8-env/lib/python3.8/site-packages/jax/linear_util.py", line 272, in memoized_fun
    ans = call(fun, *args)
  File "/build/alpa/alpa/api.py", line 203, in _compile_parallel_executable
    return method.compile_executable(fun, in_tree, out_tree_thunk,
  File "/build/alpa/alpa/parallel_method.py", line 292, in compile_executable
    return compile [...]

2022-08-11 05:24 UTC, JiahaoYao commented
The reason for the pytorch fails is because there is another `DeviceCluster` initialization. Since the placement group arranges the resources, the second resource allocation will hang the cluster forever. 

https://github.com/alpa-projects/alpa/blob/611069f5d9f1afa5f5805a822e146dfc7b0f7041/alpa/pipeline_parallel/stage_construction.py#L463-L464

2022-08-11 06:03 UTC, JiahaoYao commented
so, for me, the difficult parts are `test_zhen.py` and `test_simple.py` where you have the profiling and the profiling code uses the resources more freely, which conflicts the previous placement in alpa.

2022-08-11 15:45 UTC, JiahaoYao commented
the issue is fixed and it passed the ci

2022-08-11 15:45 UTC, JiahaoYao commented
going to refactor the code and get back to u.

2022-08-11 17:20 UTC, JiahaoYao commented
@merrymercy this pr is ready for review.

2022-08-11 17:30 UTC, JiahaoYao commented
hold on, small error.

2022-08-11 20:39 UTC, JiahaoYao commented
interesting, why the ci test for this one is forever instead of breaking?

2022-08-11 23:26 UTC, JiahaoYao commented
btw, it is green now @merrymercy

2022-08-13 02:33 UTC, merrymercy requested changes
Please also update the minimum ray requirement at https://github.com/alpa-projects/alpa/blob/792ffaa95957ed5f50f689a3c0d55169936064f0/setup.py#L85

2022-08-13 02:33 UTC, merrymercy commented on alpa/util.py
> +                                  "`pip install ray==1.13.0`.")
```suggestion
                                  "`pip install ray>=1.13.0`.")
```
Use ">="?

2022-08-13 02:33 UTC, merrymercy commented on alpa/device_mesh.py
> +            global_cluster.host_num_devices[0])
```suggestion
            global_cluster.num_hosts,
```
Use this public API

2022-08-13 02:33 UTC, merrymercy commented on alpa/util.py
> +    if should_create_placement_group:
`should_create_placement_group` is always True when using alpa along. `should_create_placement_group` can be false when using Tune integration. Is this correct?

2022-08-13 02:33 UTC, merrymercy commented on alpa/util.py
> +    # case 3:
When do we need case 3?
I guess case 1 is for tune integration and case 2 is for using alpa alone, but I don't understand case 3

2022-08-13 02:33 UTC, merrymercy commented on alpa/util.py
> +    Each bundle will be assigned to a device.
```suggestion
    Each bundle will be assigned to a node.
```

2022-08-13 02:33 UTC, merrymercy commented on alpa/util.py
> +                         "is no less than the number of device IPs.")
```suggestion
                         "is less than the number of device IPs.")
```

2022-08-13 02:33 UTC, merrymercy commented on alpa/util.py
> +    # device IP -> bundle index
We use "device" for one "gpu". Please rename all "device" to "node".

2022-08-13 02:33 UTC, merrymercy commented on alpa/util.py
> +def get_bundle2ip(pg=None):
```suggestion
def get_bundle2ip(pg: PlacementGroup = None):
```

2022-08-13 02:33 UTC, merrymercy commented on alpa/util.py
> +        device_ips (list): The list of device IP addresses.
coding style. We add type annotations to the function signature instead of the docstring.

2022-08-13 06:20 UTC, JiahaoYao reviewed
@merrymercy plz review again! ty!

2022-08-14 08:38 UTC, merrymercy commented on alpa/util.py
> +    # case 3:
1. If we change https://github.com/alpa-projects/alpa/blob/792ffaa95957ed5f50f689a3c0d55169936064f0/alpa/pipeline_parallel/stage_construction.py#L463-L464 to something like ```whole_cluster_virtual_mesh = device_mesh.global_cluster.get_virtual_physical_mesh() and do not create a cluster again, can we avoid this case?
2. Getting things from the ray global state may be dangerous if the ray cluster is not running alpa only.

2022-08-14 08:40 UTC, merrymercy commented on alpa/device_mesh.py
> +            cls = ray.remote(num_cpus=0,
The `MeshHostWorker` actually uses 1 CPU. To address your issue, can we use something like `num_cpus=1e-3`?

2022-08-14 08:41 UTC, merrymercy commented on alpa/util.py
> +    # case 3:
1. If we change https://github.com/alpa-projects/alpa/blob/792ffaa95957ed5f50f689a3c0d55169936064f0/alpa/pipeline_parallel/stage_construction.py#L463-L464 to something like ```whole_cluster_virtual_mesh = device_mesh.global_cluster.get_virtual_physical_mesh() and do not create a cluster again, can we avoid this case?
2. Getting things from the ray global state may be dangerous if the ray cluster is not running alpa only.

2022-08-15 21:08 UTC, JiahaoYao reviewed
hi @merrymercy , i have a better solution! and PTAL, tyty!

2022-08-16 11:02 UTC, merrymercy approved these changes
LGTM. Some minor naming issues.

2022-08-16 11:03 UTC, merrymercy approved these changes

2022-08-16 11:03 UTC, merrymercy commented on alpa/device_mesh.py
> +            self.device_ips.append(ip)
```suggestion
            self.node_ips.append(ip)
```

2022-08-16 11:03 UTC, merrymercy commented on alpa/device_mesh.py
> +                                                self.device_ips)
```suggestion
                                                self.node_ips)
```

2022-08-16 11:05 UTC, merrymercy commented on alpa/device_mesh.py
> +                                                self.node_ips)
```suggestion
        device_bundle_idx_list = get_bundle_idx(placement_group, self.node_ips)
```

2022-08-16 11:52 UTC, merged