[Docs] Add guide for deploy on Slurm
alpa-projects/alpa pull request #828
Opened 2022-12-22 05:39 UTC by ddxxdd-code

As mentioned by Issue #751 that the given link in the current docs for using Alpa on Ray on Slurm is broken. Hence, after using Slurm for one month, I wrote this guide, hoping to add to the tutorial section of docs and help people with access of Slurm to deploy Alpa.

2022-12-22 18:56 UTC, zhisbug requested changes

2022-12-22 18:56 UTC, zhisbug commented on docs/tutorials/alpa_on_slurm.rst
> +Alpa requires CUDA and runs on GPU. Therefore, you need access to CUDA-compatible GPU in the cluster to run Alpa.
nits: GPUs

2022-12-22 18:56 UTC, zhisbug commented on docs/tutorials/alpa_on_slurm.rst
> +        One easy way to create an environment with all dependencies installed is to create an environment using package management systems like `conda <https://docs.conda.io/en/latest/>`_ and setup t
add a section to describe how to prepare an alpa python environment on slurm (assuming slurm has a Python virutalenv manager such as conda)

2022-12-22 18:56 UTC, zhisbug commented on docs/tutorials/alpa_on_slurm.rst
> +        To run a interactive job on Slurm, use the command :code:`interact`.
once you have a section in the previous comment, you can delete this note

2022-12-22 18:56 UTC, zhisbug commented on docs/tutorials/alpa_on_slurm.rst
> +The Slurm cluster takes sbatch scripts submitted using command sbatch then queue the job specified by the script for execution.
nits: queues

2022-12-22 18:56 UTC, zhisbug commented on docs/tutorials/alpa_on_slurm.rst
> +
add a note that if some modules are missing you have to find the slurm cluster manager to prepare them.

Also, add a note about how to check if a module exists.

2022-12-22 18:56 UTC, zhisbug commented on docs/tutorials/alpa_on_slurm.rst
> +To activate a environment using package management systems like conda, add the following line:
nits: an

2022-12-22 18:56 UTC, zhisbug commented on docs/tutorials/alpa_on_slurm.rst
> +        Note here the argument gpus_per_node should not exceed the number of GPU you have on each node.
highlight

2022-12-22 18:56 UTC, zhisbug commented on docs/tutorials/alpa_on_slurm.rst
> +At this time, we have a running Ray instance and next we can run Alpa on it.
add a section to tell users to check ray is running as expected

2022-12-23 05:17 UTC, zhisbug commented
@ddxxdd-code please remove the `echo` statements in the scripts and only keep those important ones (e.g., echos that check ray is up and alpa is working fine)

2022-12-23 05:28 UTC, ddxxdd-code commented
Just updated all the scripts. All echos removed, except for the one before testing Ray status.

2022-12-31 04:46 UTC, zhisbug requested changes

2022-12-31 04:46 UTC, zhisbug commented
Also, please move the slurm_scripts_examples to under `examples/` instead of `docs/`

2023-01-02 08:33 UTC, merged