Add get mhlo module method in WarppedHlo
alpa-projects/alpa pull request #925
Opened 2023-05-10 02:41 UTC by vincentccc

2023-05-10 19:16 UTC, ZYHowell commented
LGTM, can you please reformat the code to pass the CI's formatting test

2023-05-10 19:17 UTC, ZYHowell requested changes
LGTM. Can you please format the file to pass the CI test? We have a format.sh script to help you do so.

2023-05-11 02:48 UTC, vincentccc commented
> format.sh


> LGTM. Can you please format the file to pass the CI test? We have a format.sh script to help you do so.

Thanks, already done yet

2023-05-15 01:39 UTC, ZYHowell approved these changes

2023-05-15 01:40 UTC, merged